{{- if .Values.nacos.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nacos.server.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nacos.server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nacos.replicaCount }}
  selector:
    matchLabels:
  {{- include "nacos.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "nacos.server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "nacos.server.name" . }}
          image: "{{ .Values.nacos.image.repository }}:{{ .Values.nacos.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: MODE
              value: {{ .Values.nacos.env.mode }}
          ports:
            - name: http
              containerPort: {{.Values.nacos.service.port}}
              protocol: TCP
            - name: grpc1
              containerPort: {{.Values.nacos.service.grpcPort1}}
              protocol: TCP
            - name: grpc2
              containerPort: {{.Values.nacos.service.grpcPort2}}
              protocol: TCP
          resources:
            {{- toYaml .Values.nacos.resources | nindent 12 }}
{{- end }}
