---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.name" . }}-dataservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
          app.kubernetes.io/component: dataservice
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dataservice
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
      {{- if .Values.extensions.dataservice.podAnnotations }}
      annotations:
        {{- toYaml .Values.extensions.dataservice.podAnnotations | nindent 8 }}
      {{- end }}
      annotations:
    spec:
      containers:
        - name: dataservice
          image: "{{ .Values.extensions.dataservice.image.repository }}:{{ .Values.extensions.dataservice.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.extensions.dataservice.image.pullPolicy }}
          {{- if .Values.extensions.dataservice.ports }}
          ports:
          {{- range $port := .Values.extensions.dataservice.ports }}
          - name: {{ $port.name}}
            containerPort: {{ $port.containerPort }}
            protocol: {{ $port.protocol }}
          {{- end }}
          {{- end }}
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://{{ include "otel-demo.name" . }}-otelcol:4317'
            - name: MYSQL_HOST
              value: '{{ include "otel-demo.name" . }}-mysql'
            {{- with .Values.extensions.dataservice.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}

          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.name" . }}-dataservice
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extensions.dataservice.servcie.type | default "ClusterIP" }}
  {{- if .Values.extensions.dataservice.ports }}
  ports:
  {{- range $port := .Values.extensions.dataservice.ports }}
  - name: {{ $port.name}}
    port: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
    targetPort: {{ $port.containerPort }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "otel-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dataservice
